apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metricapp
  namespace: default
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: metrics-app/
    repoURL: https://github.com/mykg/cloudraft_assignment.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: secret.password
          value: MYPASSWORD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
